### ISSUE TITLE
@container queries plugin support 

### ISSUE THREAD

**Issue by aretrace** [tailwindlabs/prettier-plugin-tailwindcss#107]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.2.0

**What version of Tailwind CSS are you using?**

v3.2.4

**What version of Node.js are you using?**

v19.1.0

**What package manager are you using?**

npm

**What operating system are you using?**

macOS

**Reproduction URL**

https://github.com/tailwindlabs/tailwindcss-container-queries/blob/main/src/index.ts

**Describe your issue**
prettier-plugin-tailwindcss does not organize @tailwindcss/container-queries plugin classes in the same order as other classes from the components layer

**Comment by reinink** [comment]
Hey! So at its core all this plugin does is organize your classes in the same order that Tailwind orders them in your CSS, and doesn't do anything special for plugins like the container queries plugin. Meaning, it *should* just work 😅

I just tested this out in Tailwind Play, and got expected results. I started with this:

```html
<div class="@container">
  <div class="p-4 bg-red-100 @lg:p-6 @lg:bg-green-300">test</div>
</div>
```

And after hitting the "Tidy" button (which runs the Tailwind Prettier sorting plugin), I get this:

```html
<div class="@container">
  <div class="bg-red-100 p-4 @lg:bg-green-300 @lg:p-6">test</div>
</div>
```

You can give this a try yourself here: https://play.tailwindcss.com/Z3bjIzCtjd

I also tested this locally in a Next.js project, and got the same results, so from what I can tell everything seems to be working correctly. Happy to have a closer look at your particular problem, but we'll need an actual reproduction — provided as either a Git repo or a Tailwind Play.

You might also find this blog post helpful, which goes into some detail about how the Tailwind CSS Prettier plugin works:

https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

Hope that helps! 💪

**Comment by reinink** [comment]
@aretrace Hey! That's correct, since the container queries plugin is loaded after the core plugins, these utilities are ordered last in the generated CSS, which is why the prettier plugin orders the `@container` class last as well.

Here is the outputted CSS from your [Tailwind Play](https://play.tailwindcss.com/MC5lFek7sK):

```css
.flex-1 {
  flex: 1 1 0%;
}

.bg-red-100 {
  --tw-bg-opacity: 1;
  background-color: rgb(254 226 226 / var(--tw-bg-opacity));
}

.p-4 {
  padding: 1rem;
}

.invert-0 {
  --tw-invert: invert(0);
  filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow);
}

.\@container {
  container-type: inline-size;
}
```

Hope that clears things up!
