### ISSUE TITLE
Prettier plugin just broke a lot of functionality on VUE code

### ISSUE THREAD

**Issue by autotel** [tailwindlabs/prettier-plugin-tailwindcss#344]
Last weekend, prettier decided to break all the html closing brackets to a new line, and remove the spaces between some of the html tags

``` vue
<Suspense>
    <template #fallback>
```

Became

``` vue
<Suspense
    > <template #fallback>
```

on several of our files

Having the template on the same line as the closing bracket of the tag made a difference for Vite compiler, not sure why.

This was our prettyfier action script:

```yaml
name: Prettier Code Formatter

on: [push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}

        # Because of bug https://github.com/creyD/prettier_action/issues/111
        - name: Install Plugins manually
          run: npm i prettier-plugin-tailwindcss

        - name: Prettify code
          uses: creyD/prettier_action@v4.3
          with:
            prettier_options: --write ./resources/**/*.{ts,vue}
            prettier_plugins: "prettier-plugin-tailwindcss"

```
