### ISSUE TITLE
Prettier plugin adds a whitespace before asterisk on functional utilities

### ISSUE THREAD

**Issue by CHC383** [tailwindlabs/prettier-plugin-tailwindcss#345]
The plugin currently formats the CSS to look like [this](https://github.com/Wombosvideo/tailwindcss-animate-v4/blob/4dae3becb75e7c33242fa84306aab1bea0889483/tailwindcss-animate.css#L96-L108)

```css
/* Code */
@utility direction-* {
  animation-direction: --value(--animation-direction-*);
}

/* Expected behavior */
@utility direction-* {
  animation-direction: --value(--animation-direction-*);
}

/* Current behavior */
@utility direction-* {
  animation-direction: --value(--animation-direction- *);
}
```

**Comment by adamwathan** [comment]
Hey! This is just Prettier actually, not our plugin:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArjAlgGyzATwAIATLAJzjG2gFoAqI4AHSiKIEMosBbDmqLTKVqWaEiK1aANw450cABRSuvfmMHCqAhgEoA3KwC+IADQgIABwEBnZKA7lyEAO4AFRwjso5LjgTtzACNyDjAAazgYAGUOHjgAGSwoOGQAMzkbOGDQiKjoyzDkgHNkGHIFcyyeLDKK7JA4AA9LOHJeBBg5ABU2qEcsOG8MnCyqkpw4AEV0CHh0zIaAKxsm6Inp2fmkEbGQAEctuDdnS28QDhtaFLgSW7MQco5cEoBhCB4+ZAucHAebDYAQRg5SwQUwxzaSRSC1GDQAFjAeDgAOrw-BDQpgODRLz4LDSfAEb5gGyBEDSBQASSgd1g0TA7WsgNp0UIk1he0sziyKNClm+3KGbWkqXMySy5BgJw4xS+O0W5kK5ElJLJD25yRgKKwJBg8OQAA4AAzmSiHCjHUJyjichpdII6vUGpAAJnM6Cy3Q4QWGisaPCCtzuJASXGK6FlcAAYhByHwQSVvhxMBAQEYjEA

Unfortunate but we made sure Tailwind will still work even with the annoying space there. Hoping to eventually try and PR something to Prettier that leaves this alone if we can.

**Comment by martinhipp** [comment]
You could add `/* prettier-ignore */` before the utility until (if ever) Prettier fixes this behaviour.

For example:
```css
/* prettier-ignore */
@utility direction-* {
  animation-direction: --value(--animation-direction-*);
}
```
