### ISSUE TITLE
Error: Cannot find module '@tailwindcss/forms'

### ISSUE THREAD

**Issue by cungminh2710** [tailwindlabs/prettier-plugin-tailwindcss#82]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.1.11

**What version of Tailwind CSS are you using?**

v3.0.22

**What version of Node.js are you using?**

v16

**What package manager are you using?**

Yarn

**What operating system are you using?**

Linux

**Reproduction**
```
name: Code Format

on: workflow_dispatch

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,tsx} --print-width 120 --use-tabs --single-quote --jsx-single-quote
          prettier_plugins: "prettier-plugin-tailwindcss@0.1.11"
```

**Describe your issue**

After upgrading from v0.1.4 -> v0.1.11, we are facing this issue when using with `creyD/prettier_action`

![image](https://user-images.githubusercontent.com/8063319/173711824-b5d5cc85-5254-43f0-aa46-594603e21b98.png)
